const part=(text,type="normal")=>({text,type});
const example=(id,ruleAudioSrc,parts)=>({id,audioSrc:`assets/audio/examples/${ruleAudioSrc}.mp3`,parts});
const rules=[
  {id:"izhar",short:"الإظهار",title:"الإظهار الحلقي",mark:"ء",className:"rule-izhar",letters:["ء","هـ","ع","ح","غ","خ"],ruleAudioSrc:"assets/audio/rules/izhar.mp3",definition:"الإظهار يعني أن ننطق النون الساكنة أو التنوين بوضوح، من غير إدغام ولا إخفاء، عندما يأتي بعدهما أحد حروف الحلق.",memory:["أخي","هاك","علمًا","حازه","غير","خاسر"],examples:[
    example("izhar-aman","izhar-aman",[part("مِ"),part("نْ","noon"),part(" "),part("آ","rule-letter"),part("مَنَ")]),example("izhar-had","izhar-had",[part("مِ"),part("نْ","noon"),part(" "),part("هَـ","rule-letter"),part("ادٍ")]),example("izhar-ilm","izhar-ilm",[part("مِ"),part("نْ","noon"),part(" "),part("عِ","rule-letter"),part("لْمٍ")]),example("izhar-hakim","izhar-hakim",[part("عَلِيمٌ","noon"),part(" "),part("حَ","rule-letter"),part("كِيمٌ")]),example("izhar-ghill","izhar-ghill",[part("مِ"),part("نْ","noon"),part(" "),part("غِ","rule-letter"),part("لٍّ")]),example("izhar-khayr","izhar-khayr",[part("مِ"),part("نْ","noon"),part(" "),part("خَ","rule-letter"),part("يْرٍ")])],note:"أول حرف من كل كلمة في العبارة يدل على حرف من حروف الإظهار."},
  {id:"idgham",short:"الإدغام",title:"الإدغام",mark:"د",className:"rule-idgham",letters:["ي","ر","م","ل","و","ن"],ruleAudioSrc:"assets/audio/rules/idgham.mp3",definition:"الإدغام يعني إدخال النون الساكنة أو التنوين في الحرف الذي يأتي بعدهما، حتى يصبحا كأنهما حرفًا واحدًا مشددًا.",memory:["يرملون"],examples:[
    example("idgham-ya","idgham-ya",[part("مَ"),part("نْ","noon"),part(" "),part("يَ","rule-letter"),part("عْمَلْ")]),example("idgham-nun","idgham-nun",[part("مِ"),part("نْ","noon"),part(" "),part("نِ","rule-letter"),part("عْمَةٍ")]),example("idgham-mim","idgham-mim",[part("مِ"),part("نْ","noon"),part(" "),part("مَ","rule-letter"),part("اءٍ")]),example("idgham-waw","idgham-waw",[part("مِ"),part("نْ","noon"),part(" "),part("وَ","rule-letter"),part("الٍ")]),example("idgham-ra","idgham-ra",[part("مِ"),part("نْ","noon"),part(" "),part("رَ","rule-letter"),part("بِّهِمْ")]),example("idgham-lam","idgham-lam",[part("مِ"),part("نْ","noon"),part(" "),part("لَ","rule-letter"),part("دُنْهُ")])],note:"لا يحدث الإدغام إذا اجتمعت النون الساكنة وحرف الإدغام في كلمة واحدة: الدُّنْيَا – بُنْيَانٌ – صِنْوَانٌ – قِنْوَانٌ؛ وحكمها إظهار مطلق."},
  {id:"iqlab",short:"الإقلاب",title:"الإقلاب",mark:"ب",className:"rule-iqlab",letters:["ب"],ruleAudioSrc:"assets/audio/rules/iqlab.mp3",definition:"الإقلاب يعني تحويل النون الساكنة أو التنوين إلى ميم مخفاة مع الغنة، عندما يأتي بعدهما حرف الباء.",memory:["حرف الإقلاب واحد فقط، وهو الباء."],examples:[
    example("iqlab-bad","iqlab-bad",[part("مِ"),part("نْ","noon"),part(" "),part("بَ","rule-letter"),part("عْدِ")]),example("iqlab-anbihum","iqlab-anbihum",[part("أَ"),part("نْ","noon"),part("بِ","rule-letter"),part("ئْهُمْ")]),example("iqlab-basir","iqlab-basir",[part("سَمِيعٌ","noon"),part(" "),part("بَ","rule-letter"),part("صِيرٌ")]),example("iqlab-bidhat","iqlab-bidhat",[part("عَلِيمٌ","noon"),part(" "),part("بِ","rule-letter"),part("ذَاتِ الصُّدُورِ")])],note:"قد تظهر في المصحف ميم صغيرة فوق النون الساكنة أو بدل حركة التنوين للدلالة على الإقلاب."},
  {id:"ikhfa",short:"الإخفاء",title:"الإخفاء الحقيقي",mark:"خ",className:"rule-ikhfa",letters:["ص","ذ","ث","ك","ج","ش","ق","س","د","ط","ز","ف","ت","ض","ظ"],ruleAudioSrc:"assets/audio/rules/ikhfa.mp3",definition:"الإخفاء هو أن ننطق النون الساكنة أو التنوين بصوت بين الإظهار والإدغام، مع غنة مقدارها حركتان.",memory:["صف","ذا","ثنا","كم","جاد","شخص","قد","سما","دم","طيبًا","زد","في","تقى","ضع","ظالمًا"],examples:[
    example("ikhfa-sad","ikhfa-sad",[part("مِ"),part("نْ","noon"),part(" "),part("صَ","rule-letter"),part("لْصَالٍ")]),example("ikhfa-dhal","ikhfa-dhal",[part("مِ"),part("نْ","noon"),part(" "),part("ذَ","rule-letter"),part("كَرٍ")]),example("ikhfa-tha","ikhfa-tha",[part("مِ"),part("نْ","noon"),part(" "),part("ثَ","rule-letter"),part("مَرَةٍ")]),example("ikhfa-kaf","ikhfa-kaf",[part("مِ"),part("نْ","noon"),part(" "),part("كُ","rule-letter"),part("لِّ")]),example("ikhfa-jim","ikhfa-jim",[part("مِ"),part("نْ","noon"),part(" "),part("جُ","rule-letter"),part("وعٍ")]),example("ikhfa-shin","ikhfa-shin",[part("مِ"),part("نْ","noon"),part(" "),part("شَ","rule-letter"),part("رٍّ")]),example("ikhfa-qaf","ikhfa-qaf",[part("مِ"),part("نْ","noon"),part(" "),part("قَ","rule-letter"),part("بْلُ")]),example("ikhfa-sin","ikhfa-sin",[part("مِ"),part("نْ","noon"),part(" "),part("سُ","rule-letter"),part("وءٍ")]),example("ikhfa-dal","ikhfa-dal",[part("مِ"),part("نْ","noon"),part(" "),part("دَ","rule-letter"),part("ابَّةٍ")]),example("ikhfa-ta","ikhfa-ta",[part("مِ"),part("نْ","noon"),part(" "),part("طَ","rule-letter"),part("يِّبَاتِ")]),example("ikhfa-zay","ikhfa-zay",[part("مِ"),part("نْ","noon"),part(" "),part("زَ","rule-letter"),part("وَالٍ")]),example("ikhfa-fa","ikhfa-fa",[part("مِ"),part("نْ","noon"),part(" "),part("فَ","rule-letter"),part("ضْلِ")]),example("ikhfa-ta2","ikhfa-ta2",[part("جَنَّاتٍ","noon"),part(" "),part("تَ","rule-letter"),part("جْرِي")]),example("ikhfa-dad","ikhfa-dad",[part("قَوْمًا","noon"),part(" "),part("ضَ","rule-letter"),part("الِّينَ")]),example("ikhfa-za","ikhfa-za",[part("ظِلًّا","noon"),part(" "),part("ظَ","rule-letter"),part("لِيلًا")])],note:"في الإخفاء لا نظهر النون كاملة، ولا ندمجها تمامًا، بل نخفيها مع الغنة."}
];

const state={completed:JSON.parse(localStorage.getItem("tajweedProgress")||"[]"),score:Number(localStorage.getItem("tajweedScore")||0),sound:localStorage.getItem("tajweedSound")!=="off",teacher:false};
const lessonsEl=document.querySelector("#lessons");
const toArabic=n=>String(n).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const esc=s=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const renderParts=(parts,reveal=true)=>parts.map((p,i)=>`<span class="${reveal&&p.type==="noon"?"focus-n":reveal&&p.type==="rule-letter"?"focus-letter":""}" data-part-index="${i}" data-part-type="${p.type}">${esc(p.text)}</span>`).join("");
const plain=parts=>parts.map(p=>p.text).join("");
const renderMemory=r=>r.memory.map(w=>r.id==="izhar"||r.id==="ikhfa"?`<span><b class="memory-letter">${esc(w[0])}</b>${esc(w.slice(1))}</span>`:esc(w)).join(" ");

function renderLessons(){lessonsEl.innerHTML=rules.map((r,i)=>`<section id="${r.id}" class="lesson ${r.className}"><div class="lesson-inner"><header class="lesson-head"><div><span class="lesson-number">المحطة ${["الأولى","الثانية","الثالثة","الرابعة"][i]}</span><h2>${r.title}</h2></div><div class="lesson-symbol">${r.mark}</div></header><div class="lesson-body"><article class="card"><h3>ماذا يعني؟</h3><p>${r.definition}</p><h3>حروف ${r.short}</h3><div class="letters">${r.letters.map(l=>`<span class="letter">${l}</span>`).join("")}</div>${r.id==="idgham"?`<div class="subrules"><div class="subrule"><h4>إدغام بغنة: «ينمو»</h4><p>ي – ن – م – و، مع غنة مقدارها حركتان.</p></div><div class="subrule"><h4>إدغام بغير غنة</h4><p>ل – ر، إدغام من غير غنة.</p></div></div>`:""}<div class="note">${r.note}</div><div class="teacher-note"><strong>للمعلّمة:</strong> اطلب من الطلاب تحديد النون أو التنوين أولًا، ثم الحرف التالي قبل تسمية الحكم.</div></article><div><article class="card memory"><h3>مفتاح الحفظ</h3><blockquote>«${renderMemory(r)}»</blockquote></article><article class="card examples-card"><h3>أمثلة واضحة</h3><div class="examples">${r.examples.map(e=>`<button class="example" data-audio="${e.audioSrc}" aria-label="تشغيل مثال ${plain(e.parts)}">${renderParts(e.parts)}</button>`).join("")}</div><div class="action-row"><button class="soft-button listen" data-audio="${r.ruleAudioSrc}">🔊 استمع إلى ${r.short}</button><button class="soft-button complete-button ${state.completed.includes(r.id)?"completed":""}" data-complete="${r.id}">${state.completed.includes(r.id)?"✓ تمّ الدرس":"تمّ الدرس"}</button></div></article></div></div></div></section>`).join("")}
function renderProgress(){document.querySelector("#lesson-progress").innerHTML=rules.map(r=>`<span title="${r.short}" class="progress-cell ${state.completed.includes(r.id)?"done":""}"></span>`).join("");document.querySelector("#progress-count").textContent=`${toArabic(state.completed.length)} من ٤`}
function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove("show"),3000)}

let currentAudio=null;
const sfxFiles={correct:"correct.mp3",wrong:"wrong.mp3",applause:"applause.mp3","level-complete":"level-complete.mp3",click:"click.mp3"};
function playFile(src,{fallback=false}={}){if(!state.sound)return Promise.resolve(false);if(currentAudio)currentAudio.pause();currentAudio=new Audio(src);return currentAudio.play().then(()=>true).catch(()=>{if(fallback)tone("click");toast("التسجيل الصوتي غير مضاف بعد؛ سيبقى النشاط متاحًا.");return false})}
function synthTone(kind){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),osc=ctx.createOscillator(),gain=ctx.createGain();const map={click:[420,.05],correct:[660,.16],wrong:[180,.2],applause:[740,.35],"level-complete":[520,.35]};const [freq,dur]=map[kind]||map.click;osc.frequency.value=freq;osc.type=kind==="wrong"?"sawtooth":"sine";gain.gain.setValueAtTime(.08,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+dur)}catch{}}
function tone(kind){if(!state.sound)return;const audio=new Audio(`assets/audio/sfx/${sfxFiles[kind]||sfxFiles.click}`);audio.volume=.65;audio.play().catch(()=>synthTone(kind))}
const encouragements=["أحسنت!","رائع جدًا!","إجابة ممتازة!","أبدعت!","اختيار موفق!","تقدم رائع!","ممتاز، استمر!"];let lastEncouragement=-1;
function encourage(){let i;do{i=Math.floor(Math.random()*encouragements.length)}while(i===lastEncouragement);lastEncouragement=i;return encouragements[i]}
function confetti(){if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const layer=document.querySelector("#confetti"),colors=["#2878b8","#66bfea","#e9b949","#42a66b","#8a64c5","#ed8a43"],count=35+Math.floor(Math.random()*16);for(let i=0;i<count;i++){const el=document.createElement("i");el.className="confetti-piece";el.style.left=`${Math.random()*100}%`;el.style.background=colors[i%colors.length];el.style.animationDelay=`${Math.random()*.3}s`;el.style.setProperty("--drift",`${-90+Math.random()*180}px`);layer.append(el);setTimeout(()=>el.remove(),2400)}}
function celebrate(container,message,explanation=""){tone("correct");confetti();container?.classList.add("pulse");setTimeout(()=>container?.classList.remove("pulse"),500);return `${message||encourage()}${explanation?`<span class="explain">${explanation}</span>`:""}`}
function fisherYates(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}

renderLessons();renderProgress();
document.addEventListener("click",e=>{const complete=e.target.closest("[data-complete]");if(complete){const id=complete.dataset.complete;if(!state.completed.includes(id)){state.completed.push(id);localStorage.setItem("tajweedProgress",JSON.stringify(state.completed));tone("level-complete");confetti()}complete.classList.add("completed");complete.textContent="✓ تمّ الدرس";renderProgress();toast("أحسنت! اكتمل هذا الدرس.")}const listen=e.target.closest("[data-audio]");if(listen)playFile(listen.dataset.audio,{fallback:true})});

const classifyQuestions=[
  [rules[2].examples[0],"الإقلاب","لأن بعد النون الساكنة حرف الباء."],[rules[0].examples[5],"الإظهار","لأن بعد النون الساكنة حرف الخاء."],[rules[1].examples[0],"الإدغام","لأن بعد النون الساكنة حرف الياء."],[rules[3].examples[5],"الإخفاء","لأن بعد النون الساكنة حرف الشين."],[rules[2].examples[2],"الإقلاب","لأن بعد التنوين حرف الباء."],[rules[0].examples[3],"الإظهار","لأن بعد التنوين حرف الحاء."],[rules[1].examples[4],"الإدغام","لأن بعد النون الساكنة حرف الراء."],[rules[3].examples[6],"الإخفاء","لأن بعد النون الساكنة حرف القاف."]];
const revealQuestions=[
  ["ما حكم النون الساكنة في: مِنْ خَيْرٍ؟","إظهار حلقي؛ لأن بعد النون حرف الخاء."],["ما حكم النون الساكنة في: مِنْ بَعْدِ؟","إقلاب؛ لأن بعد النون حرف الباء."],["ما حكم النون الساكنة في: مَنْ يَعْمَلْ؟","إدغام بغنة؛ لأن بعد النون حرف الياء."],["ما حكم التنوين في: عَلِيمٌ حَكِيمٌ؟","إظهار حلقي؛ لأن بعد التنوين حرف الحاء."],["ما حكم النون الساكنة في: مِنْ شَرٍّ؟","إخفاء؛ لأن بعد النون حرف الشين."]];
const tfQuestions=[
  ["حروف الإظهار ستة.",true,"حروفه: ء هـ ع ح غ خ."],["حرف الإقلاب هو الميم.",false,"حرف الإقلاب هو الباء."],["حروف الإدغام مجموعة في كلمة يرملون.",true,"العبارة صحيحة."],["الإدغام بغير غنة مع الياء والواو.",false,"يكون مع اللام والراء."],["للإخفاء خمسة عشر حرفًا.",true,"العبارة صحيحة."],["حروف الإدغام بغنة مجموعة في كلمة ينمو.",true,"العبارة صحيحة."],["الراء من حروف الإدغام بغنة.",false,"الراء من الإدغام بغير غنة."],["الباء هو حرف الإقلاب.",true,"العبارة صحيحة."]];
const sortRounds=[["ء","ع","ي","ر","ب","ص","ك","ت"],["هـ","ح","م","ل","ب","ذ","ج","ق"],["غ","خ","و","ن","ب","س","د","ط"],["ء","هـ","ي","و","ب","ز","ف","ض"]];
const ruleForLetter=l=>rules.find(r=>r.letters.includes(l))?.id;
const findQuestions=[rules[0].examples[5],rules[2].examples[0],rules[1].examples[0],rules[3].examples[5],rules[0].examples[3],rules[3].examples[6]];
const dragCards=[rules[0].examples[5],rules[1].examples[0],rules[2].examples[0],rules[3].examples[5],rules[0].examples[3],rules[3].examples[6]];
let game={type:"classify",index:0,score:0,order:fisherYates(classifyQuestions),placed:{},selected:null,locked:false};
const stage=()=>document.querySelector("#game-stage");
function gameMeta(total){return `<div class="game-meta"><span>${toArabic(game.index+1)} / ${toArabic(total)}</span><span>النتيجة: ${toArabic(game.score)}</span></div>`}
function gameResult(type,total){stage().innerHTML=`<div class="result-panel"><span>اكتملت الجولة</span><br><strong>${toArabic(game.score)} / ${toArabic(total)}</strong><h3>${game.score===total?"إتقان رائع!":"تقدم جميل، ويمكن تحسين النتيجة بالمحاولة التالية."}</h3><button class="primary-button" data-restart="${type}">أعد الجولة</button></div>`;tone("applause");confetti()}
function bins(className="sort-bin"){return rules.map(r=>`<button class="${className} ${r.className}" data-bin="${r.id}"><strong>${r.short}</strong><div class="bin-items"></div></button>`).join("")}
function renderGame(type=game.type){game.type=type;game.locked=false;const s=stage();if(type==="classify"){if(game.index>=8)return gameResult(type,8);const [q]=game.order[game.index];s.innerHTML=`<h3>صنّف الحكم</h3>${gameMeta(8)}<p>ما الحكم في المثال؟</p><div class="game-example">${renderParts(q.parts)}</div><div class="choices">${rules.map(r=>`<button class="choice" data-answer="${r.short}">${r.short}</button>`).join("")}</div><div class="feedback"></div>`}
  if(type==="sort"){if(game.index>=4)return gameResult(type,4);const letters=fisherYates(sortRounds[game.index]);game.placed={};s.innerHTML=`<h3>رتّب الحروف</h3>${gameMeta(4)}<p>اختر حرفًا ثم اختر الحكم المناسب، أو اسحبه إلى مكانه.</p><div class="sort-letters">${letters.map(l=>`<button draggable="true" class="sort-letter" data-letter="${l}">${l}</button>`).join("")}</div><div class="sort-bins">${bins()}</div><button class="soft-button" id="check-sort">تحقق من الجولة</button><div class="feedback"></div>`;enableDrag()}
  if(type==="reveal"){if(game.index>=revealQuestions.length)return gameResult(type,revealQuestions.length);const q=revealQuestions[game.index];s.innerHTML=`<h3>اكشف الجواب</h3>${gameMeta(revealQuestions.length)}<p>فكّر أولًا، ثم افتح البطاقة.</p><div class="reveal-card" tabindex="0"><h4>${q[0]}</h4><p class="answer">${q[1]}</p><small>اضغط للكشف</small></div><button class="soft-button next-reveal" disabled>السؤال التالي</button>`}
  if(type==="truefalse"){if(game.index>=8)return gameResult(type,8);const q=tfQuestions[game.index];s.innerHTML=`<h3>صح أم خطأ؟</h3>${gameMeta(8)}<div class="game-example">${q[0]}</div><div class="tf-buttons"><button data-tf="true">✓ صح</button><button data-tf="false">✕ خطأ</button></div><div class="feedback"></div>`}
  if(type==="findrule"){if(game.index>=6)return gameResult(type,6);const q=findQuestions[game.index];s.innerHTML=`<h3>أين الحكم؟</h3>${gameMeta(6)}<p>حدد جزأين: موضع النون أو التنوين، ثم الحرف المؤثر.</p><div class="find-parts">${q.parts.map((p,i)=>`<button class="find-part" data-find="${i}">${esc(p.text)}</button>`).join("")}</div><button class="soft-button" id="check-find">تحقق</button><div class="feedback"></div>`;game.selected=[]}
  if(type==="drag"){if(game.index>=1)return gameResult(type,6);game.placed={};s.innerHTML=`<h3>اسحب المثال</h3><div class="game-meta"><span>٦ بطاقات</span><span>النتيجة تظهر بعد التحقق</span></div><p>اسحب كل مثال إلى الحكم الصحيح، أو اختر البطاقة ثم المنطقة.</p><div class="drag-cards">${fisherYates(dragCards).map(q=>`<button draggable="true" class="drag-card" data-card="${q.id}">${esc(plain(q.parts))}</button>`).join("")}</div><div class="drag-bins">${bins("drag-bin")}</div><button class="soft-button" id="check-drag">تحقق من البطاقات</button><div class="feedback"></div>`;enableDrag()}}
function resetGame(type){game={type,index:0,score:0,order:type==="classify"?fisherYates(classifyQuestions):[],placed:{},selected:null,locked:false};renderGame(type)}
function advance(delay=1950){game.locked=true;setTimeout(()=>{game.index++;renderGame()},delay)}
function feedback(){return stage().querySelector(".feedback")}
function enableDrag(){stage().querySelectorAll("[draggable=true]").forEach(el=>el.addEventListener("dragstart",e=>e.dataTransfer.setData("text/plain",el.dataset.letter||el.dataset.card)));stage().querySelectorAll("[data-bin]").forEach(bin=>{bin.addEventListener("dragover",e=>{e.preventDefault();bin.classList.add("dragover")});bin.addEventListener("dragleave",()=>bin.classList.remove("dragover"));bin.addEventListener("drop",e=>{e.preventDefault();bin.classList.remove("dragover");placeItem(e.dataTransfer.getData("text/plain"),bin)})})}
function placeItem(key,bin){const el=stage().querySelector(`[data-letter="${CSS.escape(key)}"],[data-card="${CSS.escape(key)}"]`);if(!el)return;game.placed[key]=bin.dataset.bin;bin.querySelector(".bin-items").append(" ",el.textContent);el.remove()}
renderGame();
document.querySelector(".game-tabs").addEventListener("click",e=>{const type=e.target.dataset.game;if(!type)return;document.querySelectorAll(".game-tabs button").forEach(b=>b.classList.toggle("active",b===e.target));resetGame(type)});
stage().addEventListener("click",e=>{if(game.locked)return;const restart=e.target.dataset.restart;if(restart)return resetGame(restart);const f=feedback();if(e.target.dataset.answer){const [,correct,why]=game.order[game.index],ok=e.target.dataset.answer===correct;if(ok){game.score++;e.target.classList.add("correct");f.className="feedback good";f.innerHTML=celebrate(stage(),encourage(),why);advance()}else{e.target.classList.add("wrong");tone("wrong");f.className="feedback try";f.innerHTML=`حاول مرة أخرى.<span class="explain">ابحث عن الحرف الذي يأتي بعد النون الساكنة أو التنوين.</span>`}return}
  const selectable=e.target.closest(".sort-letter,.drag-card");if(selectable){stage().querySelectorAll(".sort-letter,.drag-card").forEach(x=>x.classList.remove("selected"));selectable.classList.add("selected");game.selected=selectable.dataset.letter||selectable.dataset.card;return}const bin=e.target.closest("[data-bin]");if(bin&&game.selected){placeItem(game.selected,bin);game.selected=null;return}
  if(e.target.id==="check-sort"){const all=sortRounds[game.index],ok=all.every(l=>game.placed[l]===ruleForLetter(l));if(ok){game.score++;f.className="feedback good";f.innerHTML=celebrate(stage());advance()}else{tone("wrong");f.className="feedback try";f.textContent="راجع التصنيف؛ ستُعاد الجولة لتجربة ترتيب جديد.";game.locked=true;setTimeout(()=>renderGame(),1500)}return}
  const reveal=e.target.closest(".reveal-card");if(reveal){reveal.classList.add("open");stage().querySelector(".next-reveal").disabled=false;return}if(e.target.classList.contains("next-reveal")){game.score++;game.index++;renderGame();return}
  if(e.target.dataset.tf){const q=tfQuestions[game.index],ok=(e.target.dataset.tf==="true")===q[1];if(ok){game.score++;f.className="feedback good";f.innerHTML=celebrate(stage(),encourage(),q[2]);advance()}else{tone("wrong");f.className="feedback try";f.innerHTML=`حاول مرة أخرى.<span class="explain">${q[2]}</span>`}return}
  if(e.target.dataset.find!==undefined){const i=Number(e.target.dataset.find);e.target.classList.toggle("selected");game.selected.includes(i)?game.selected=game.selected.filter(x=>x!==i):game.selected.push(i);return}if(e.target.id==="check-find"){const q=findQuestions[game.index],need=q.parts.map((p,i)=>p.type!=="normal"?i:-1).filter(i=>i>=0),ok=game.selected.length===need.length&&need.every(i=>game.selected.includes(i));if(ok){q.parts.forEach((p,i)=>{const el=stage().querySelector(`[data-find="${i}"]`);if(p.type==="noon")el.classList.add("revealed-noon");if(p.type==="rule-letter")el.classList.add("revealed-rule")});game.score++;f.className="feedback good";f.innerHTML=celebrate(stage(),encourage(),"تم تحديد موضع النون أو التنوين والحرف المؤثر.");advance()}else{tone("wrong");f.className="feedback try";f.textContent="حدد الموضعين فقط: النون أو التنوين، والحرف الذي يليه."}return}
  if(e.target.id==="check-drag"){const ok=dragCards.every(q=>game.placed[q.id]===rules.find(r=>r.examples.includes(q)).id);if(ok){game.score=6;f.className="feedback good";f.innerHTML=celebrate(stage(),"أبدعت!","وُضعت البطاقات الست في أحكامها الصحيحة.");advance()}else{tone("wrong");f.className="feedback try";f.textContent="راجع البطاقات؛ ستُعاد الجولة لإعادة المحاولة.";game.locked=true;setTimeout(()=>renderGame(),1500)}}
});

const quizBank=[
  ["ما حكم «مِنْ بَعْدِ»؟",["إظهار","إدغام","إقلاب","إخفاء"],"إقلاب"],["كم عدد حروف الإظهار؟",["١","٤","٦","١٥"],"٦"],["ما حرف الإقلاب؟",["م","ب","ن","و"],"ب"],["أي كلمة تجمع حروف الإدغام؟",["ينمو","يرملون","قطب جد","أخي هاك"],"يرملون"],["ما حروف الإدغام بغير غنة؟",["ي، و","م، ن","ل، ر","ع، ح"],"ل، ر"],["ما حكم «مِنْ خَيْرٍ»؟",["إظهار","إدغام","إقلاب","إخفاء"],"إظهار"],["كم عدد حروف الإخفاء؟",["٦","١٥","٤","١"],"١٥"],["ما حكم «مَنْ يَعْمَلْ»؟",["إظهار","إدغام بغنة","إقلاب","إخفاء"],"إدغام بغنة"],["أكمل كلمة حروف الإدغام: يرملـ…",["ون","ان","يم","بن"],"ون"],["غنة الإخفاء مقدارها…",["حركة","حركتان","أربع حركات","لا غنة"],"حركتان"],["ما حكم «مِنْ شَرٍّ»؟",["إخفاء","إظهار","إقلاب","إدغام"],"إخفاء"],["أي حرف من حروف الإظهار؟",["ص","ب","خ","ت"],"خ"],["أي حرف من حروف الإخفاء؟",["ع","هـ","ق","ر"],"ق"],["ما حكم «غَفُورٌ رَحِيمٌ»؟",["إدغام بغير غنة","إخفاء","إظهار","إقلاب"],"إدغام بغير غنة"]];
let quiz=[],quizPos=0,quizScore=0;
function updateBest(){document.querySelector("#best-score").textContent=state.score?`أفضل نتيجة: ${toArabic(state.score)} / ١٠`:""}updateBest();
document.querySelector("#quiz-card").addEventListener("click",e=>{if(e.target.id==="start-quiz"||e.target.id==="retry-quiz"){quiz=fisherYates(quizBank).slice(0,10);quizPos=0;quizScore=0;showQuiz()}if(e.target.dataset.quizAnswer){if(e.target.dataset.quizAnswer===quiz[quizPos][2]){quizScore++;tone("correct")}else tone("wrong");quizPos++;quizPos<10?showQuiz():showResult()}if(e.target.id==="review-rules")document.querySelector("#map").scrollIntoView()});
function showQuiz(){const q=quiz[quizPos];document.querySelector("#quiz-card").innerHTML=`<div class="quiz-question"><div class="quiz-meta"><b>السؤال ${toArabic(quizPos+1)} من ١٠</b><span>النتيجة في النهاية</span></div><div class="quiz-bar"><span style="width:${(quizPos+1)*10}%"></span></div><h3>${q[0]}</h3><div class="quiz-options">${fisherYates(q[1]).map(o=>`<button class="quiz-option" data-quiz-answer="${o}">${o}</button>`).join("")}</div></div>`}
function showResult(){if(quizScore>state.score){state.score=quizScore;localStorage.setItem("tajweedScore",state.score)}updateBest();const msg=quizScore===10?"إتقان رائع!":quizScore>=8?"ممتاز جدًا!":quizScore>=6?"أداء جميل، بقي القليل!":"محاولة جميلة، لنكرر التحدي!";tone("level-complete");confetti();document.querySelector("#quiz-card").innerHTML=`<div class="result"><span class="logo-wrap"><img src="logo.jpeg" alt="شعار Milestone School"></span><strong>${toArabic(quizScore)} / ١٠</strong><h3>${msg}</h3><div class="action-row"><button id="retry-quiz" class="primary-button">أعد الاختبار</button><button id="review-rules" class="soft-button">راجع الأحكام</button></div></div>`}

document.querySelector("#sound-toggle").addEventListener("click",e=>{state.sound=!state.sound;localStorage.setItem("tajweedSound",state.sound?"on":"off");e.currentTarget.setAttribute("aria-pressed",state.sound);e.currentTarget.classList.toggle("active",!state.sound);e.currentTarget.firstChild.textContent=state.sound?"🔊 ":"🔇 ";if(state.sound)tone("click")});
if(!state.sound){const soundButton=document.querySelector("#sound-toggle");soundButton.setAttribute("aria-pressed","false");soundButton.classList.add("active");soundButton.firstChild.textContent="🔇 "}
document.querySelector("#teacher-mode").addEventListener("click",e=>{state.teacher=!state.teacher;document.body.classList.toggle("teacher-on",state.teacher);e.currentTarget.classList.toggle("active",state.teacher);e.currentTarget.setAttribute("aria-pressed",state.teacher);toast(state.teacher?"تم تشغيل إرشادات المعلّمة.":"تم إخفاء إرشادات المعلّمة.")});
document.querySelector(".menu-toggle").addEventListener("click",e=>{const links=document.querySelector("#nav-links");links.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",links.classList.contains("open"))});
document.querySelector("#back-top").addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));addEventListener("scroll",()=>document.querySelector("#back-top").classList.toggle("show",scrollY>650));
document.querySelector("#reset-progress").addEventListener("click",()=>{if(confirm("هل تريد حذف التقدم ونتيجة الاختبار؟")){localStorage.removeItem("tajweedProgress");localStorage.removeItem("tajweedScore");location.reload()}});
