const examplesById=new Map(window.QURAN_EXAMPLES.map(example=>[example.id,example]));
const lessonExampleIds={
  izhar:["izhar-01","izhar-07","izhar-09","izhar-15","izhar-17","izhar-23"],
  idgham:["idgham-ghunnah-01","idgham-ghunnah-08","idgham-ghunnah-11","idgham-ghunnah-18","idgham-without-02","idgham-without-10"],
  iqlab:["iqlab-01","iqlab-05","iqlab-10","iqlab-15"],
  ikhfa:["ikhfa-01","ikhfa-04","ikhfa-05","ikhfa-08","ikhfa-09","ikhfa-12","ikhfa-13","ikhfa-16","ikhfa-17","ikhfa-20","ikhfa-21","ikhfa-24","ikhfa-25","ikhfa-28","ikhfa-29"]
};
const lessonAuxiliaryExampleIds={idgham:["absolute-dunya","absolute-bunyan","absolute-sinwan","absolute-qinwan"]};
const rules=[
  {id:"izhar",short:"الإظهار",title:"الإظهار الحلقي",mark:"ء",className:"rule-izhar",letters:["ء","هـ","ع","ح","غ","خ"],definition:"الإظهار يعني أن ننطق النون الساكنة أو التنوين بوضوح، من غير إدغام ولا إخفاء، عندما يأتي بعدهما أحد حروف الحلق.",memory:["أخي","هاك","علمًا","حازه","غير","خاسر"],note:"أول حرف من كل كلمة في العبارة يدل على حرف من حروف الإظهار."},
  {id:"idgham",short:"الإدغام",title:"الإدغام",mark:"د",className:"rule-idgham",letters:["ي","ر","م","ل","و","ن"],definition:"الإدغام يعني إدخال النون الساكنة أو التنوين في الحرف الذي يأتي بعدهما، حتى يصبحا كأنهما حرفًا واحدًا مشددًا.",memory:["يرملون"],note:"لا يحدث الإدغام إذا اجتمعت النون الساكنة وحرف الإدغام في كلمة واحدة: الدُّنْيَا – بُنْيَانٌ – صِنْوَانٌ – قِنْوَانٌ؛ وحكمها إظهار مطلق."},
  {id:"iqlab",short:"الإقلاب",title:"الإقلاب",mark:"ب",className:"rule-iqlab",letters:["ب"],definition:"الإقلاب يعني تحويل النون الساكنة أو التنوين إلى ميم مخفاة مع الغنة، عندما يأتي بعدهما حرف الباء.",memory:["حرف الإقلاب واحد فقط، وهو الباء."],note:"قد تظهر في المصحف ميم صغيرة فوق النون الساكنة أو بدل حركة التنوين للدلالة على الإقلاب."},
  {id:"ikhfa",short:"الإخفاء",title:"الإخفاء الحقيقي",mark:"خ",className:"rule-ikhfa",letters:["ص","ذ","ث","ك","ج","ش","ق","س","د","ط","ز","ف","ت","ض","ظ"],definition:"الإخفاء هو أن ننطق النون الساكنة أو التنوين بصوت بين الإظهار والإدغام، مع غنة مقدارها حركتان.",memory:["صف","ذا","ثنا","كم","جاد","شخص","قد","سما","دم","طيبًا","زد","في","تقى","ضع","ظالمًا"],note:"في الإخفاء لا نظهر النون كاملة، ولا ندمجها تمامًا، بل نخفيها مع الغنة."}
].map(rule=>({...rule,examples:lessonExampleIds[rule.id].map(id=>examplesById.get(id))}));

class ExampleManager{
  constructor(bank){this.bank=bank;this.usedExampleIds=new Set();this.activityUsage=new Map();this.triggerUsage=new Map();this.targetUsage=new Map();this.subtypeUsage=new Map();this.visibleLessonRules=new Set();this.activitySerial=0}
  nextActivityKey(prefix){this.activitySerial++;return `${prefix}-${this.activitySerial}`}
  markUsed(example,activityKey="session"){if(!example)return null;this.usedExampleIds.add(example.id);if(!this.activityUsage.has(activityKey))this.activityUsage.set(activityKey,new Set());this.activityUsage.get(activityKey).add(example.id);this.triggerUsage.set(example.triggerLetter,(this.triggerUsage.get(example.triggerLetter)||0)+1);const targetKey=`${example.rule}:${example.targetType}`;this.targetUsage.set(targetKey,(this.targetUsage.get(targetKey)||0)+1);if(example.subtype)this.subtypeUsage.set(example.subtype,(this.subtypeUsage.get(example.subtype)||0)+1);return example}
  markLessonVisible(ruleId){if(this.visibleLessonRules.has(ruleId))return;this.visibleLessonRules.add(ruleId);[...(lessonExampleIds[ruleId]||[]),...(lessonAuxiliaryExampleIds[ruleId]||[])].forEach(id=>this.markUsed(examplesById.get(id),`lesson:${ruleId}`))}
  matches(example,rule,options){if(example.rule!==rule)return false;if(options.subtype&&example.subtype!==options.subtype)return false;if(options.subtypes&&!options.subtypes.includes(example.subtype))return false;if(options.targetType&&example.targetType!==options.targetType)return false;if(options.triggerLetters&&!options.triggerLetters.includes(example.triggerLetter))return false;if(options.excludeIds?.has(example.id))return false;return true}
  getUnusedExample(rule,options={}){const activityKey=options.activityKey||"session",activityUsed=this.activityUsage.get(activityKey)||new Set(),candidates=this.bank.filter(example=>this.matches(example,rule,options));if(!candidates.length)return null;const pools=[candidates.filter(example=>!this.usedExampleIds.has(example.id)),candidates.filter(example=>!activityUsed.has(example.id)),candidates];const pool=pools.find(items=>items.length);const score=example=>(this.triggerUsage.get(example.triggerLetter)||0)*100+(this.targetUsage.get(`${example.rule}:${example.targetType}`)||0)*10+(example.subtype?(this.subtypeUsage.get(example.subtype)||0):0);const best=Math.min(...pool.map(score)),balanced=pool.filter(example=>score(example)===best),selected=fisherYates(balanced)[0];return this.markUsed(selected,activityKey)}
  getUnusedExamples(rule,count,options={}){const selected=[],excludeIds=new Set(options.excludeIds||[]);while(selected.length<count){const example=this.getUnusedExample(rule,{...options,excludeIds});if(!example)break;selected.push(example);excludeIds.add(example.id)}return selected}
}
const exampleManager=new ExampleManager(window.QURAN_EXAMPLES);
window.exampleManager=exampleManager;

const state={completed:JSON.parse(localStorage.getItem("tajweedProgress")||"[]"),score:Number(localStorage.getItem("tajweedScore")||0),sound:localStorage.getItem("tajweedSound")!=="off",teacher:false};
const lessonsEl=document.querySelector("#lessons");
const toArabic=n=>String(n).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const esc=s=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const renderParts=(parts,reveal=true)=>parts.map((p,i)=>`<span class="${reveal&&p.type==="noon"?"focus-n":reveal&&p.type==="rule-letter"?"focus-letter":""}" data-part-index="${i}" data-part-type="${p.type}">${esc(p.text)}</span>`).join("");
const plain=parts=>parts.map(p=>p.text).join("");
const renderMemory=r=>r.memory.map(w=>r.id==="izhar"||r.id==="ikhfa"?`<span><b class="memory-letter">${esc(w[0])}</b>${esc(w.slice(1))}</span>`:esc(w)).join(" ");

function renderLessons(){lessonsEl.innerHTML=rules.map((r,i)=>`<section id="${r.id}" class="screen lesson ${r.className}" data-screen-title="${r.short}"><div class="screen-content lesson-inner"><header class="lesson-head"><div><span class="lesson-number">المحطة ${["الأولى","الثانية","الثالثة","الرابعة"][i]}</span><h2>${r.title}</h2></div><div class="lesson-symbol">${r.mark}</div></header><div class="lesson-body"><article class="card"><h3>ماذا يعني؟</h3><p>${r.definition}</p><h3>حروف ${r.short}</h3><div class="letters">${r.letters.map(l=>`<span class="letter">${l}</span>`).join("")}</div>${r.id==="idgham"?`<div class="subrules"><div class="subrule"><h4>إدغام بغنة: «ينمو»</h4><p>ي – ن – م – و، مع غنة مقدارها حركتان.</p></div><div class="subrule"><h4>إدغام بغير غنة</h4><p>ل – ر، إدغام من غير غنة.</p></div></div>`:""}<div class="note">${r.note}</div><div class="teacher-note"><strong>للمعلّمة:</strong> اطلب من الطلاب تحديد النون أو التنوين أولًا، ثم الحرف التالي قبل تسمية الحكم.</div></article><div><article class="card memory"><h3>مفتاح الحفظ</h3><blockquote>«${renderMemory(r)}»</blockquote></article><article class="card examples-card"><h3>أمثلة واضحة</h3><div class="examples">${r.examples.map(e=>`<button type="button" class="example" data-example-id="${e.id}" aria-label="مثال ${plain(e.parts)}">${renderParts(e.parts)}</button>`).join("")}</div><div class="action-row"><button class="soft-button complete-button ${state.completed.includes(r.id)?"completed":""}" data-complete="${r.id}">${state.completed.includes(r.id)?"✓ تمّ الدرس":"تمّ الدرس"}</button><button class="primary-button challenge-button" data-start-challenge="${r.id}">ابدأ التحدي</button></div></article></div></div></div><div class="screen-navigation" data-nav-slot data-prev="${i?rules[i-1].id:"map"}" data-home="map" data-next="${i<rules.length-1?rules[i+1].id:"compare"}"></div></section>`).join("")}
function renderProgress(){document.querySelector("#lesson-progress").innerHTML=rules.map(r=>`<span title="${r.short}" class="progress-cell ${state.completed.includes(r.id)?"done":""}"></span>`).join("");document.querySelector("#progress-count").textContent=`${toArabic(state.completed.length)} من ٤`}
function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove("show"),3000)}

let currentAudio=null;
const sfxFiles={wrong:"assets/audio/sfx/wrong.mp3","level-complete":"assets/audio/sfx/level-complete.mp3",click:"assets/audio/sfx/click.mp3",applause:"صوت_تصفيق_جمهور_للمونتاج_مؤثراتMP3_70K.mp3"};
function playFile(src,{fallback=false}={}){if(!state.sound)return Promise.resolve(false);if(currentAudio)currentAudio.pause();currentAudio=new Audio(src);return currentAudio.play().then(()=>true).catch(()=>{if(fallback)tone("click");toast("التسجيل الصوتي غير مضاف بعد؛ سيبقى النشاط متاحًا.");return false})}
function synthTone(kind){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),osc=ctx.createOscillator(),gain=ctx.createGain();const map={click:[420,.05],correct:[660,.16],wrong:[180,.2],applause:[740,.35],"level-complete":[520,.35]};const [freq,dur]=map[kind]||map.click;osc.frequency.value=freq;osc.type=kind==="wrong"?"sawtooth":"sine";gain.gain.setValueAtTime(.08,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+dur)}catch{}}
class SfxManager{
  constructor(files){this.files=files;this.cache=new Map();this.current=null;this.segmentTimer=null}
  preload(name){if(!this.files[name])return null;if(!this.cache.has(name)){const audio=new Audio(this.files[name]);audio.preload="auto";audio.volume=.65;this.cache.set(name,audio);audio.load()}return this.cache.get(name)}
  stop(){clearTimeout(this.segmentTimer);this.segmentTimer=null;if(this.current){this.current.pause();this.current.currentTime=0;this.current=null}}
  stopQuran(){if(currentAudio){currentAudio.pause();currentAudio.currentTime=0;currentAudio=null}}
  async play(name){if(!state.sound)return false;this.stopQuran();this.stop();const audio=this.preload(name);if(!audio)return false;audio.currentTime=0;this.current=audio;audio.onended=()=>{if(this.current===audio)this.current=null};try{await audio.play();return true}catch{if(this.current===audio)this.current=null;return false}}
  async playSegment(name,duration=2000){if(!state.sound)return false;this.stopQuran();this.stop();const audio=this.preload(name);if(!audio)return false;audio.currentTime=0;this.current=audio;try{await audio.play();this.segmentTimer=setTimeout(()=>{if(this.current===audio){audio.pause();audio.currentTime=0;this.current=null}this.segmentTimer=null},duration);return true}catch{if(this.current===audio)this.current=null;return false}}
}
const sfxManager=new SfxManager(sfxFiles);
const playSfxSegment=(name,duration=2000)=>sfxManager.playSegment(name,duration);
const playApplause=({duration=2000}={})=>playSfxSegment("applause",duration);
window.sfxManager=sfxManager;
window.playSfxSegment=playSfxSegment;
window.playApplause=playApplause;
function tone(kind){if(!state.sound)return;if(kind==="correct"||kind==="applause"){playApplause({duration:2000});return}sfxManager.play(kind).then(played=>{if(!played&&state.sound&&kind!=="wrong")synthTone(kind)})}
sfxManager.preload("applause");
const encouragements=["أحسنت!","رائع جدًا!","إجابة ممتازة!","أبدعت!","اختيار موفق!","تقدم رائع!","ممتاز، استمر!"];let lastEncouragement=-1;
function encourage(){let i;do{i=Math.floor(Math.random()*encouragements.length)}while(i===lastEncouragement);lastEncouragement=i;return encouragements[i]}
function confetti(amount){if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const layer=document.querySelector("#confetti"),colors=["#2878b8","#66bfea","#e9b949","#42a66b","#8a64c5","#ed8a43"],count=amount||35+Math.floor(Math.random()*16);for(let i=0;i<count;i++){const el=document.createElement("i");el.className="confetti-piece";el.style.left=`${Math.random()*100}%`;el.style.background=colors[i%colors.length];el.style.animationDelay=`${Math.random()*.3}s`;el.style.setProperty("--drift",`${-90+Math.random()*180}px`);layer.append(el);setTimeout(()=>el.remove(),2400)}}
function celebrate(container,message,explanation=""){tone("correct");confetti();container?.classList.add("pulse");setTimeout(()=>container?.classList.remove("pulse"),500);return `${message||encourage()}${explanation?`<span class="explain">${explanation}</span>`:""}`}
const wrongText="انتبه أكثر يا عسول 💛";
function setAnswerLock(root,locked){root?.querySelectorAll(".answer-card").forEach(card=>{card.disabled=locked;card.classList.toggle("is-disabled",locked)})}
function showCorrect(card,root,feedbackEl,message,explanation=""){card?.classList.add("is-correct");setAnswerLock(root,true);if(card){card.classList.remove("is-disabled");card.disabled=true}feedbackEl.className="feedback good";feedbackEl.innerHTML=celebrate(root,message||encourage(),explanation)}
function showWrong(card,root,feedbackEl,explanation="",unlock=()=>{}){card?.classList.add("is-wrong");setAnswerLock(root,true);if(card)card.classList.remove("is-disabled");tone("wrong");feedbackEl.className="feedback try";feedbackEl.innerHTML=`${wrongText}${explanation?`<span class="explain">${explanation}</span>`:""}`;setTimeout(()=>{card?.classList.remove("is-wrong");setAnswerLock(root,false);unlock()},800)}
function fisherYates(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}

renderLessons();renderProgress();

const challengeRoot=document.querySelector("#challenge-screens");
challengeRoot.innerHTML=rules.map(r=>`<section id="challenge-${r.id}" class="screen section challenge-screen ${r.className}" data-screen-title="تحدي ${r.short}"><div class="screen-content challenge-scroll-content"><div class="challenge-shell"><div class="challenge-progress"></div><div class="challenge-card"></div></div></div><button class="soft-button challenge-exit" data-screen="${r.id}">خروج</button></section><section id="result-${r.id}" class="screen section result-screen ${r.className}" data-screen-title="نتيجة ${r.short}"><div class="rule-result-content result-panel"></div></section>`).join("");

const screenOrder=["welcome","intro","map","izhar","idgham","iqlab","ikhfa","compare","games","quiz"];
let currentScreen="welcome",screenHistory=[];

function renderNavigation(){document.querySelectorAll("[data-nav-slot]").forEach(slot=>{const prev=slot.dataset.prev,next=slot.dataset.next,home=slot.dataset.home;slot.innerHTML=`${prev?`<button class="nav-button prev-button" data-screen="${prev}">السابق</button>`:""}${home?`<button class="nav-button home-button" data-screen="${home}">اختيار الأحكام</button>`:""}${next?`<button class="nav-button next-button" data-screen="${next}">التالي</button>`:""}`})}

function showScreen(id,{remember=true,direction="auto"}={}){const target=document.getElementById(id);if(!target||id===currentScreen)return;const old=document.getElementById(currentScreen);if(remember&&old)screenHistory.push(currentScreen);const oldIndex=screenOrder.indexOf(currentScreen),newIndex=screenOrder.indexOf(id);const forward=direction==="next"||(direction==="auto"&&newIndex>=0&&oldIndex>=0&&newIndex>oldIndex);old?.classList.remove("active","enter-next","enter-prev");target.classList.remove("enter-next","enter-prev");target.classList.add("active",forward?"enter-next":"enter-prev");currentScreen=id;document.body.dataset.currentScreen=id;if(lessonExampleIds[id])exampleManager.markLessonVisible(id);document.querySelector("#teacher-panel").hidden=true;document.querySelector("#teacher-mode").setAttribute("aria-expanded","false");target.querySelector("button:not([disabled]), [tabindex='0']")?.focus({preventScroll:true});tone("click")}

renderNavigation();
document.querySelector(".teacher-screen-list").innerHTML=screenOrder.map(id=>`<button type="button" data-screen="${id}">${document.getElementById(id)?.dataset.screenTitle||id}</button>`).join("");
document.addEventListener("click",e=>{const screenButton=e.target.closest("[data-screen]");if(screenButton){showScreen(screenButton.dataset.screen);return}const challenge=e.target.closest("[data-start-challenge]");if(challenge)return startChallenge(challenge.dataset.startChallenge);const teacherStage=e.target.closest("[data-teacher-stage]");if(teacherStage)startChallenge(teacherStage.dataset.teacherRule,Number(teacherStage.dataset.teacherStage),true)});

const welcomeScreen=document.querySelector("#welcome"),journeyCta=document.querySelector(".journey-cta"),reduceMotion=matchMedia("(prefers-reduced-motion: reduce)");
journeyCta.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();if(journeyCta.classList.contains("is-pressed"))return;journeyCta.classList.add("is-pressed");welcomeScreen.classList.add("is-launching");setTimeout(()=>{showScreen("intro");journeyCta.classList.remove("is-pressed");welcomeScreen.classList.remove("is-launching")},reduceMotion.matches?120:360)});
if(matchMedia("(pointer:fine)").matches&&!reduceMotion.matches){let parallaxFrame=0;welcomeScreen.addEventListener("pointermove",e=>{cancelAnimationFrame(parallaxFrame);parallaxFrame=requestAnimationFrame(()=>{const rect=welcomeScreen.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width-.5,y=(e.clientY-rect.top)/rect.height-.5;welcomeScreen.querySelectorAll("[data-parallax]").forEach(el=>{const factor=Number(el.dataset.parallax)||0;el.style.setProperty("--parallax-x",`${x*12*factor}px`);el.style.setProperty("--parallax-y",`${y*9*factor}px`)})})});welcomeScreen.addEventListener("pointerleave",()=>{cancelAnimationFrame(parallaxFrame);welcomeScreen.querySelectorAll("[data-parallax]").forEach(el=>{el.style.setProperty("--parallax-x","0px");el.style.setProperty("--parallax-y","0px")})})}

document.addEventListener("keydown",e=>{if(e.defaultPrevented||e.altKey||e.ctrlKey||e.metaKey||e.target.matches("input,textarea,select,[contenteditable=true]"))return;if(!["ArrowLeft","ArrowRight"].includes(e.key))return;const screen=document.getElementById(currentScreen),slot=screen?.querySelector("[data-nav-slot]");if(!slot)return;const destination=e.key==="ArrowLeft"?slot.dataset.next:slot.dataset.prev;if(destination){e.preventDefault();showScreen(destination,{direction:e.key==="ArrowLeft"?"next":"prev"})}});

const ruleChallenges={
  izhar:[
    {id:"izhar-letters",title:"التقط الحروف",type:"letter-pick",prompt:"اختر حروف الإظهار",options:["ء","هـ","ع","ح","غ","خ","ب","ق","ر","ت"],correctAnswer:["ء","هـ","ع","ح","غ","خ"],explanation:"اكتملت حروف الإظهار الستة: ء هـ ع ح غ خ."},
    {id:"izhar-cause",title:"اكتشف السبب",type:"cause-tap",prompt:"ما الحرف الذي جعل الحكم إظهارًا؟",correctAnswer:"rule-letter",explanation:"حدد الحرف الذي يلي النون الساكنة أو التنوين."},
    {id:"izhar-memory",title:"مفتاح الحفظ",type:"memory-complete",prompt:"أكمل مفتاح الحفظ",memoryWords:["أخي","هاك","علمًا","حازه","غير","خاسر"],options:["خاسر","قادر","جميل","بعيد"],correctAnswer:"خاسر",explanation:"أوائل الكلمات تجمع حروف الإظهار: ء هـ ع ح غ خ."},
    {id:"izhar-intruder",title:"اكتشف الدخيل",type:"intruder",prompt:"أي مثال لا ينتمي إلى الإظهار؟",options:[],correctAnswer:null,explanation:""},
    {id:"izhar-apply",title:"طبّق القاعدة",type:"choice",prompt:"ما سبب الإظهار هنا؟",usesExample:true,options:["لأن الحرف التالي من حروف الإظهار","لأن بعد النون حرف الباء","لأن النون مشددة","لأن بعدها حرف إدغام"],correctAnswer:"لأن الحرف التالي من حروف الإظهار",explanation:""}
  ],
  idgham:[
    {id:"idgham-ghunnah-letters",title:"حروف الغنة",type:"letter-pick",prompt:"اختر حروف الإدغام بغنة",options:["ي","ن","م","و","ل","ر","ب","ع"],correctAnswer:["ي","ن","م","و"],successVisual:"ينمو",explanation:"حروف الإدغام بغنة مجموعة في كلمة «ينمو»."},
    {id:"idgham-kind",title:"بغنة أم بغير غنة؟",type:"duel",prompt:"ما نوع الإدغام هنا؟",usesExample:true,options:["إدغام بغنة","إدغام بغير غنة"],correctAnswer:null,explanation:""},
    {id:"idgham-cause",title:"اكتشف السبب",type:"cause-tap",prompt:"اضغط على الحرف الذي سبب الإدغام",correctAnswer:"rule-letter",explanation:"حدد الحرف الذي يلي النون الساكنة أو التنوين."},
    {id:"idgham-intruder",title:"اكتشف الدخيل",type:"intruder",prompt:"أي مثال ليس إدغامًا؟",options:[],correctAnswer:null,explanation:""},
    {id:"idgham-special",title:"حالة خاصة",type:"duel",prompt:"هل نطبّق الإدغام هنا؟",usesExample:true,options:["نعم","لا"],correctAnswer:"لا",explanation:"لأن النون الساكنة وحرف الإدغام جاءا في الكلمة نفسها، والحكم هنا إظهار مطلق."}
  ],
  iqlab:[
    {id:"iqlab-letter",title:"حرف الإقلاب",type:"letter-pick",prompt:"ما حرف الإقلاب؟",options:["م","ب","ن","و","ر"],correctAnswer:["ب"],explanation:"الباء هي حرف الإقلاب الوحيد."},
    {id:"iqlab-cause",title:"اكتشف السبب",type:"cause-tap",prompt:"اضغط على الحرف الذي سبب الإقلاب",correctAnswer:"rule-letter",explanation:"الباء هي حرف الإقلاب."},
    {id:"iqlab-action",title:"ماذا يحدث؟",type:"choice",prompt:"عند الإقلاب، ماذا يحدث للنون الساكنة أو التنوين؟",options:["تظهر كما هي","تدغم","تقلب ميمًا مخفاة مع الغنة","تحذف"],correctAnswer:"تقلب ميمًا مخفاة مع الغنة",explanation:"تُقلب النون أو التنوين ميمًا مخفاة مع غنة."},
    {id:"iqlab-example",title:"اختر المثال",type:"intruder",prompt:"أي مثال يحتوي على إقلاب؟",options:[],correctAnswer:null,explanation:""},
    {id:"iqlab-transform",title:"حوّل بصريًا",type:"equation",prompt:"أكمل التحويل",display:"نْ + ب = ؟",options:["نْ","مْ","ي","ر"],correctAnswer:"مْ",successVisual:"نْ + ب  ↓  مْ مخفاة مع غنة",explanation:"عند الباء تُقلب النون الساكنة ميمًا مخفاة مع غنة."}
  ],
  ikhfa:[
    {id:"ikhfa-letters",title:"اصطد الحروف",type:"letter-pick",prompt:"اختر حروف الإخفاء من المجموعة",options:["ص","ذ","ث","ك","ج","ش","ب","ع","ر","هـ"],correctAnswer:["ص","ذ","ث","ك","ج","ش"],explanation:"هذه ستة من حروف الإخفاء الخمسة عشر."},
    {id:"ikhfa-cause",title:"اكتشف السبب",type:"cause-tap",prompt:"ما الحرف الذي سبب الإخفاء؟",correctAnswer:"rule-letter",explanation:"حدد الحرف الذي يلي النون الساكنة أو التنوين."},
    {id:"ikhfa-memory",title:"أكمل بيت الحفظ",type:"memory-complete",prompt:"أكمل بيت حفظ حروف الإخفاء",memoryWords:["صف","ذا","ثنا","كم","جاد","شخص","قد","سما","دم","طيبًا","زد","في","تقى","ضع","ظالمًا"],options:["ظالمًا","خاسرًا","عليمًا","قادرًا"],correctAnswer:"ظالمًا",explanation:"أوائل كلمات البيت تدل على حروف الإخفاء الخمسة عشر."},
    {id:"ikhfa-intruder",title:"اكتشف الدخيل",type:"intruder",prompt:"أي مثال ليس إخفاءً؟",options:[],correctAnswer:null,explanation:""},
    {id:"ikhfa-count",title:"عدد الحروف",type:"choice",prompt:"كم عدد حروف الإخفاء؟",options:["٦","١٥","٤","١"],correctAnswer:"١٥",explanation:"للإخفاء خمسة عشر حرفًا."}
  ]
};

const challengeExample=id=>examplesById.get(id);
const challengeOptionValue=option=>typeof option==="string"?option:option.value;
const ruleDisplayName=example=>example.rule==="izhar"?"الإظهار":example.rule==="iqlab"?"الإقلاب":example.rule==="ikhfa"?"الإخفاء":example.subtype==="ghunnah"?"الإدغام بغنة":"الإدغام بغير غنة";
const exampleExplanation=example=>`لأن ${example.targetType==="tanween"?"بعد التنوين":"بعد النون الساكنة"} حرف ${example.triggerLetter}.`;
function prepareChallengeQuestions(ruleId,activityKey,onlyIndex=null){
  const questions=ruleChallenges[ruleId].map(question=>({...question,options:Array.isArray(question.options)?[...question.options]:question.options}));
  const otherRules={izhar:"iqlab",idgham:"ikhfa",iqlab:"izhar",ikhfa:"idgham"};
  for(const [questionIndex,question] of questions.entries()){
    if(onlyIndex!==null&&questionIndex!==onlyIndex)continue;
    if(question.type==="cause-tap"){
      const example=exampleManager.getUnusedExample(ruleId,{activityKey});
      question.exampleId=example.id;
      question.explanation=exampleExplanation(example);
    }
    if(question.type==="intruder"){
      if(question.id==="iqlab-example"){
        const correct=exampleManager.getUnusedExample("iqlab",{activityKey});
        const distractors=["izhar","idgham","ikhfa"].map(rule=>exampleManager.getUnusedExample(rule,{activityKey}));
        question.options=fisherYates([correct,...distractors]).map(example=>({value:example.id,exampleId:example.id}));
        question.correctAnswer=correct.id;
        question.explanation=`«${correct.text}» مثال على الإقلاب؛ لأن بعد النون الساكنة أو التنوين حرف الباء.`;
      }else{
        const own=exampleManager.getUnusedExamples(ruleId,3,{activityKey});
        const other=exampleManager.getUnusedExample(otherRules[ruleId],{activityKey});
        question.options=fisherYates([...own,other]).map(example=>({value:example.id,exampleId:example.id}));
        question.correctAnswer=other.id;
        question.explanation=`«${other.text}» حكمه ${ruleDisplayName(other)}؛ ${exampleExplanation(other)}`;
      }
    }
    if(question.usesExample&&question.type!=="equation"){
      const requestedRule=question.id==="idgham-special"?"izhar-mutlaq":ruleId;
      const example=exampleManager.getUnusedExample(requestedRule,{activityKey});
      question.exampleId=example.id;
      question.display=example.text;
      if(question.id==="idgham-kind"){
        question.correctAnswer=example.subtype==="ghunnah"?"إدغام بغنة":"إدغام بغير غنة";
        question.explanation=exampleExplanation(example);
      }
      if(question.id==="izhar-apply")question.explanation=exampleExplanation(example);
    }
  }
  return questions;
}
function renderChallengeOption(option){const value=challengeOptionValue(option),ex=typeof option==="object"&&option.exampleId?challengeExample(option.exampleId):null;return `<button class="challenge-option answer-card" data-challenge-option="${esc(value)}">${ex?renderParts(ex.parts):esc(typeof option==="string"?option:option.label||value)}</button>`}
function renderChallengeMemory(q,reveal=false){return `<div class="memory-phrase ${reveal?"is-revealed":""}">${q.memoryWords.map((word,i)=>i===q.memoryWords.length-1&&!reveal?`<span class="memory-blank">____</span>`:`<span>${reveal?`<b class="memory-initial">${esc(word[0])}</b>${esc(word.slice(1))}`:esc(word)}</span>`).join("<i>–</i>")}</div>`}
function renderChallengeActivity(q){if(q.type==="letter-pick")return `<div class="challenge-letter-grid">${fisherYates(q.options).map(letter=>`<button class="challenge-letter answer-card" data-challenge-letter="${esc(letter)}">${esc(letter)}</button>`).join("")}</div>`;if(q.type==="cause-tap"){const ex=challengeExample(q.exampleId);return `<div class="touch-example">${ex.parts.map((p,i)=>p.text.trim()?`<button class="challenge-part answer-card" data-challenge-part="${i}" data-part-type="${p.type}">${esc(p.text)}</button>`:`<span>${esc(p.text)}</span>`).join("")}</div>`}if(q.type==="memory-complete")return `${renderChallengeMemory(q)}<div class="challenge-options">${fisherYates(q.options).map(renderChallengeOption).join("")}</div>`;const displayExample=q.exampleId&&challengeExample(q.exampleId);return `${q.display?`<div class="challenge-display ${q.type==="equation"?"challenge-equation":""}">${displayExample?renderParts(displayExample.parts):esc(q.display)}</div>`:""}<div class="challenge-options ${q.type==="duel"?"option-duel":""} ${q.type==="intruder"?"intruder-options":""}">${fisherYates(q.options).map(renderChallengeOption).join("")}</div>`}

let challengeState={rule:null,questions:[],index:0,score:0,mistakesCount:0,stageMistakes:0,selected:new Set(),completedIds:[],locked:false,teacherSingle:false};
function startChallenge(id,index=0,teacherSingle=false){const activityKey=exampleManager.nextActivityKey(`challenge:${id}`);challengeState={rule:rules.find(r=>r.id===id),questions:prepareChallengeQuestions(id,activityKey,teacherSingle?index:null),index,score:0,mistakesCount:0,stageMistakes:0,selected:new Set(),completedIds:[],locked:false,teacherSingle};renderChallenge();showScreen(`challenge-${id}`)}
function renderChallenge(){const {rule,questions,index}=challengeState,q=questions[index],screen=document.querySelector(`#challenge-${rule.id}`);challengeState.stageMistakes=0;challengeState.selected=new Set();challengeState.locked=false;screen.querySelector(".challenge-progress").innerHTML=`<strong>المرحلة ${toArabic(index+1)} / ٥</strong><span>${esc(q.title)}</span>`;screen.querySelector(".challenge-card").innerHTML=`<span class="challenge-kind">${esc(q.title)}</span><h2>${esc(q.prompt)}</h2>${renderChallengeActivity(q)}<div class="challenge-success-visual" aria-live="polite"></div><div class="feedback" aria-live="polite"></div>`}
function recordChallengeMistake(){challengeState.mistakesCount++;challengeState.stageMistakes++}
function revealChallengeAnswer(q,card){const shell=card.closest(".challenge-card");if(q.type==="cause-tap"){const ex=challengeExample(q.exampleId);shell.querySelector(".touch-example").innerHTML=renderParts(ex.parts,true)}if(q.type==="memory-complete")shell.querySelector(".memory-phrase").outerHTML=renderChallengeMemory(q,true);if(q.type==="intruder"&&card){const selected=q.options.find(o=>challengeOptionValue(o)===card.dataset.challengeOption),ex=selected?.exampleId&&challengeExample(selected.exampleId);if(ex)card.innerHTML=renderParts(ex.parts,true)}if(q.successVisual)shell.querySelector(".challenge-success-visual").textContent=q.successVisual}
function completeChallengeStage(card){const q=challengeState.questions[challengeState.index],shell=card.closest(".challenge-card"),feedback=shell.querySelector(".feedback");challengeState.locked=true;challengeState.score++;challengeState.completedIds.push(q.id);showCorrect(card,shell,feedback,encourage(),q.explanation);revealChallengeAnswer(q,card);setTimeout(()=>{if(challengeState.teacherSingle)return showRuleResult();challengeState.index++;challengeState.index<5?renderChallenge():showRuleResult()},2150)}
function challengeWrong(card,detail=""){const shell=card.closest(".challenge-card"),feedback=shell.querySelector(".feedback");challengeState.locked=true;recordChallengeMistake();showWrong(card,shell,feedback,detail,()=>{challengeState.locked=false;shell.querySelectorAll("[data-challenge-letter]").forEach(button=>{if(challengeState.selected.has(button.dataset.challengeLetter)){button.disabled=true;button.classList.add("is-correct")}})})}
function showRuleResult(){const {rule,questions,score,mistakesCount,teacherSingle,index}=challengeState,result=document.querySelector(`#result-${rule.id} .rule-result-content`),i=rules.indexOf(rule),next=rules[i+1]?.id||"compare",total=teacherSingle?1:5,shownScore=teacherSingle?1:score,msg=shownScore===total?"إتقان رائع!":shownScore>=4?"ممتاز جدًا!":shownScore>=3?"أداء جميل!":"لنكرر التدريب مرة أخرى";result.innerHTML=`<span>أحسنت!</span><h2>${teacherSingle?`أنهيت نشاط ${esc(questions[index].title)}`:`أنهيت تحدي ${rule.short}`}</h2><strong>${toArabic(shownScore)} / ${toArabic(total)}</strong><h3>${msg}</h3><p>عدد المحاولات التي احتاجت تصحيحًا: ${toArabic(mistakesCount)}</p><div class="result-actions"><button class="primary-button" ${teacherSingle?`data-teacher-rule="${rule.id}" data-teacher-stage="${index}"`:`data-start-challenge="${rule.id}"`}>${teacherSingle?"إعادة النشاط":"إعادة التحدي"}</button><button class="soft-button" data-screen="map">اختيار الأحكام</button><button class="soft-button" data-screen="${next}">الحكم التالي</button></div>`;tone("level-complete");confetti();showScreen(`result-${rule.id}`)}

document.querySelector(".teacher-challenge-list").innerHTML=`<h4>مراحل التحديات</h4>${rules.map(rule=>`<details><summary>${rule.short}</summary><div>${ruleChallenges[rule.id].map((q,i)=>`<button data-teacher-rule="${rule.id}" data-teacher-stage="${i}">${toArabic(i+1)}. ${esc(q.title)}</button>`).join("")}</div></details>`).join("")}`;
challengeRoot.addEventListener("click",e=>{if(challengeState.locked)return;const q=challengeState.questions[challengeState.index],letter=e.target.closest("[data-challenge-letter]");if(letter){const value=letter.dataset.challengeLetter;if(challengeState.selected.has(value))return;if(q.correctAnswer.includes(value)){challengeState.selected.add(value);letter.classList.add("is-correct");letter.disabled=true;tone("click");const feedback=letter.closest(".challenge-card").querySelector(".feedback");feedback.className="feedback good";feedback.textContent=`أحسنت! ${value} اختيار صحيح.`;if(challengeState.selected.size===q.correctAnswer.length)completeChallengeStage(letter)}else challengeWrong(letter,"اختر حرفًا من حروف الحكم.");return}const partButton=e.target.closest("[data-challenge-part]");if(partButton){partButton.dataset.partType===q.correctAnswer?completeChallengeStage(partButton):challengeWrong(partButton,"ابحث عن الحرف الذي يأتي بعد النون الساكنة أو التنوين.");return}const option=e.target.closest("[data-challenge-option]");if(option){option.dataset.challengeOption===String(q.correctAnswer)?completeChallengeStage(option):challengeWrong(option,"راجع القاعدة وحاول مرة أخرى.")}});
document.addEventListener("click",e=>{const complete=e.target.closest("[data-complete]");if(complete){const id=complete.dataset.complete;if(!state.completed.includes(id)){state.completed.push(id);localStorage.setItem("tajweedProgress",JSON.stringify(state.completed));tone("level-complete");confetti()}complete.classList.add("completed");complete.textContent="✓ تمّ الدرس";renderProgress();toast("أحسنت! اكتمل هذا الدرس.")}const listen=e.target.closest("[data-audio]");if(listen)playFile(listen.dataset.audio,{fallback:true})});

let classifyQuestions=[],revealQuestions=[],findQuestions=[],dragCards=[];
const theoryTfQuestions=[
  ["حروف الإظهار ستة.",true,"حروفه: ء هـ ع ح غ خ."],["حرف الإقلاب هو الميم.",false,"حرف الإقلاب هو الباء."],["حروف الإدغام مجموعة في كلمة يرملون.",true,"العبارة صحيحة."],["الإدغام بغير غنة مع الياء والواو.",false,"يكون مع اللام والراء."],["للإخفاء خمسة عشر حرفًا.",true,"العبارة صحيحة."],["حروف الإدغام بغنة مجموعة في كلمة ينمو.",true,"العبارة صحيحة."],["الراء من حروف الإدغام بغنة.",false,"الراء من الإدغام بغير غنة."],["الباء هو حرف الإقلاب.",true,"العبارة صحيحة."]];
let tfQuestions=[...theoryTfQuestions];
const sortRounds=[["ء","ع","ي","ر","ب","ص","ك","ت"],["هـ","ح","م","ل","ب","ذ","ج","ق"],["غ","خ","و","ن","ب","س","د","ط"],["ء","هـ","ي","و","ب","ز","ف","ض"]];
const ruleForLetter=l=>rules.find(r=>r.letters.includes(l))?.id;
const broadRuleName=example=>example.rule==="idgham"?"الإدغام":ruleDisplayName(example);
function balancedRuleExamples(count,activityKey){const order=fisherYates(["izhar","idgham","iqlab","ikhfa"]),result=[];for(let i=0;i<count;i++){const rule=order[i%order.length],example=exampleManager.getUnusedExample(rule,{activityKey,excludeIds:new Set(result.map(item=>item.id))});if(example)result.push(example)}return result}
function prepareGameExamples(type,activityKey){if(type==="classify")classifyQuestions=balancedRuleExamples(8,activityKey).map(example=>[example,broadRuleName(example),exampleExplanation(example)]);if(type==="reveal")revealQuestions=balancedRuleExamples(5,activityKey).map(example=>["ما حكم المثال الآتي؟",`${ruleDisplayName(example)}؛ ${exampleExplanation(example)}`,example]);if(type==="findrule")findQuestions=balancedRuleExamples(6,activityKey);if(type==="drag")dragCards=balancedRuleExamples(6,activityKey);if(type==="truefalse"){const dynamic=balancedRuleExamples(4,activityKey).map((example,index)=>{const correct=index%2===0,shown=correct?broadRuleName(example):broadRuleName({rule:["izhar","idgham","iqlab","ikhfa"].find(rule=>rule!==example.rule),subtype:null});return [`المثال الآتي حكمه ${shown}.`,correct,`حكم المثال هو ${ruleDisplayName(example)}؛ ${exampleExplanation(example)}`,example]});tfQuestions=fisherYates([...dynamic,...fisherYates(theoryTfQuestions).slice(0,4)])}}
let game={type:"classify",index:0,score:0,order:[],placed:{},selected:null,locked:false};
const stage=()=>document.querySelector("#game-stage");
function gameMeta(total){return `<div class="game-meta"><span>${toArabic(game.index+1)} / ${toArabic(total)}</span><span>النتيجة: ${toArabic(game.score)}</span></div>`}
function gameResult(type,total){document.querySelector("#game-result-content").innerHTML=`<span>أحسنتم!</span><br><strong>${toArabic(game.score)} / ${toArabic(total)}</strong><h3>${game.score===total?"إتقان رائع!":"تقدم جميل، ويمكن تحسين النتيجة بالمحاولة التالية."}</h3><div class="result-actions"><button class="primary-button" data-restart-game="${type}">إعادة اللعبة</button><button class="soft-button" data-screen="games">الألعاب</button><button class="soft-button" data-screen="map">اختيار الأحكام</button></div>`;tone("level-complete");confetti();showScreen("game-result")}
function bins(className="sort-bin"){return rules.map(r=>`<button class="${className} answer-card ${r.className}" data-bin="${r.id}"><strong>${r.short}</strong><div class="bin-items"></div></button>`).join("")}
function renderGame(type=game.type){game.type=type;game.locked=false;const s=stage();if(type==="classify"){if(game.index>=8)return gameResult(type,8);const [q]=game.order[game.index];s.innerHTML=`<h3>صنّف الحكم</h3>${gameMeta(8)}<p>ما الحكم في المثال؟</p><div class="game-example">${renderParts(q.parts)}</div><div class="choices">${rules.map(r=>`<button class="choice answer-card" data-answer="${r.short}">${r.short}</button>`).join("")}</div><div class="feedback"></div>`}
  if(type==="sort"){if(game.index>=4)return gameResult(type,4);const letters=fisherYates(sortRounds[game.index]);game.placed={};s.innerHTML=`<h3>رتّب الحروف</h3>${gameMeta(4)}<p>اختر حرفًا ثم اختر الحكم المناسب، أو اسحبه إلى مكانه.</p><div class="sort-letters">${letters.map(l=>`<button draggable="true" class="sort-letter answer-card" data-letter="${l}">${l}</button>`).join("")}</div><div class="sort-bins">${bins()}</div><div class="feedback"></div>`;enableDrag()}
  if(type==="reveal"){if(game.index>=revealQuestions.length)return gameResult(type,revealQuestions.length);const q=revealQuestions[game.index];s.innerHTML=`<h3>اكشف الجواب</h3>${gameMeta(revealQuestions.length)}<p>فكّر أولًا، ثم افتح البطاقة.</p><div class="reveal-card answer-card" tabindex="0"><h4>${q[0]}</h4><div class="game-example">${renderParts(q[2].parts)}</div><p class="answer">${q[1]}</p><small>اضغط للكشف</small></div><button class="soft-button next-reveal" disabled>السؤال التالي</button>`}
  if(type==="truefalse"){if(game.index>=8)return gameResult(type,8);const q=tfQuestions[game.index];s.innerHTML=`<h3>صح أم خطأ؟</h3>${gameMeta(8)}<div class="game-example">${q[0]}${q[3]?`<span class="example-inline">${renderParts(q[3].parts)}</span>`:""}</div><div class="tf-buttons"><button class="answer-card" data-tf="true">صح</button><button class="answer-card" data-tf="false">خطأ</button></div><div class="feedback"></div>`}
  if(type==="findrule"){if(game.index>=6)return gameResult(type,6);const q=findQuestions[game.index];s.innerHTML=`<h3>أين الحكم؟</h3>${gameMeta(6)}<p>حدد جزأين: موضع النون أو التنوين، ثم الحرف المؤثر.</p><div class="find-parts">${q.parts.map((p,i)=>`<button class="find-part answer-card" data-find="${i}">${esc(p.text)}</button>`).join("")}</div><button class="soft-button" id="check-find">تحقق</button><div class="feedback"></div>`;game.selected=[]}
  if(type==="drag"){if(game.index>=1)return gameResult(type,6);game.placed={};s.innerHTML=`<h3>اسحب المثال</h3><div class="game-meta"><span>٦ بطاقات</span><span>تقييم فوري لكل حركة</span></div><p>اسحب كل مثال إلى الحكم الصحيح، أو اختر البطاقة ثم المنطقة.</p><div class="drag-cards">${fisherYates(dragCards).map(q=>`<button draggable="true" class="drag-card answer-card" data-card="${q.id}">${renderParts(q.parts)}</button>`).join("")}</div><div class="drag-bins">${bins("drag-bin")}</div><div class="feedback"></div>`;enableDrag()}}
function resetGame(type){const activityKey=exampleManager.nextActivityKey(`game:${type}`);prepareGameExamples(type,activityKey);game={type,index:0,score:0,order:type==="classify"?fisherYates(classifyQuestions):[],placed:{},selected:null,locked:false};renderGame(type)}
function advance(delay=2150){game.locked=true;setTimeout(()=>{game.index++;renderGame()},delay)}
function feedback(){return stage().querySelector(".feedback")}
function enableDrag(){stage().querySelectorAll("[draggable=true]").forEach(el=>el.addEventListener("dragstart",e=>e.dataTransfer.setData("text/plain",el.dataset.letter||el.dataset.card)));stage().querySelectorAll("[data-bin]").forEach(bin=>{bin.addEventListener("dragover",e=>{e.preventDefault();bin.classList.add("dragover")});bin.addEventListener("dragleave",()=>bin.classList.remove("dragover"));bin.addEventListener("drop",e=>{e.preventDefault();bin.classList.remove("dragover");placeItem(e.dataTransfer.getData("text/plain"),bin)})})}
function placeItem(key,bin){const root=stage(),el=root.querySelector(`[data-letter="${CSS.escape(key)}"],[data-card="${CSS.escape(key)}"]`);if(!el||game.locked)return;const expected=game.type==="sort"?ruleForLetter(key):examplesById.get(key)?.rule,f=root.querySelector(".feedback");game.locked=true;if(expected!==bin.dataset.bin){showWrong(bin,root,f,"ضع البطاقة مع الحكم المناسب.",()=>{el.classList.remove("is-wrong");game.locked=false});el.classList.add("is-wrong");return}game.placed[key]=bin.dataset.bin;game.selected=null;el.classList.add("is-correct");bin.classList.add("is-correct");setAnswerLock(root,true);tone("click");f.className="feedback good";f.innerHTML=`أحسنت! موضع صحيح.<span class="explain">${bin.querySelector("strong").textContent}</span>`;const needed=game.type==="sort"?sortRounds[game.index].length:dragCards.length,complete=Object.keys(game.placed).length===needed;setTimeout(()=>{bin.classList.remove("is-correct");bin.querySelector(".bin-items").append(" ",el.textContent);el.remove();if(complete){if(game.type==="sort")game.score++;else game.score=dragCards.length;f.innerHTML=celebrate(root,"رائع! اكتملت المجموعة.");advance()}else{setAnswerLock(root,false);game.locked=false}},650)}
const gameTitles={classify:"اكتشف الحكم",sort:"اجمع الحروف",reveal:"اكشف الجواب",truefalse:"صح أم خطأ",findrule:"أين الحكم؟",drag:"اسحب المثال"};
document.querySelector(".games-hub").addEventListener("click",e=>{const type=e.target.closest("[data-open-game]")?.dataset.openGame;if(!type)return;document.querySelector("#active-game-title").textContent=gameTitles[type];document.querySelector("#header-game-title").textContent=gameTitles[type];resetGame(type);showScreen("game-play")});
document.querySelector("#game-result").addEventListener("click",e=>{const type=e.target.closest("[data-restart-game]")?.dataset.restartGame;if(type){resetGame(type);showScreen("game-play")}});
stage().addEventListener("click",e=>{if(game.locked)return;const restart=e.target.dataset.restart;if(restart)return resetGame(restart);const f=feedback();if(e.target.dataset.answer){const [,correct,why]=game.order[game.index],ok=e.target.dataset.answer===correct;game.locked=true;if(ok){game.score++;showCorrect(e.target,stage(),f,encourage(),why);advance()}else showWrong(e.target,stage(),f,"راجع الحرف الذي يأتي بعد النون الساكنة أو التنوين.",()=>{game.locked=false});return}
  const selectable=e.target.closest(".sort-letter,.drag-card");if(selectable){stage().querySelectorAll(".sort-letter,.drag-card").forEach(x=>x.classList.remove("selected"));selectable.classList.add("selected");game.selected=selectable.dataset.letter||selectable.dataset.card;return}const bin=e.target.closest("[data-bin]");if(bin&&game.selected){placeItem(game.selected,bin);game.selected=null;return}
  const reveal=e.target.closest(".reveal-card");if(reveal){reveal.classList.add("open");stage().querySelector(".next-reveal").disabled=false;return}if(e.target.classList.contains("next-reveal")){game.score++;game.index++;renderGame();return}
  if(e.target.dataset.tf){const q=tfQuestions[game.index],ok=(e.target.dataset.tf==="true")===q[1];game.locked=true;if(ok){game.score++;showCorrect(e.target,stage(),f,encourage(),q[2]);advance()}else showWrong(e.target,stage(),f,"حاول التفكير في القاعدة مرة أخرى.",()=>{game.locked=false});return}
  if(e.target.dataset.find!==undefined){const i=Number(e.target.dataset.find);e.target.classList.toggle("selected");game.selected.includes(i)?game.selected=game.selected.filter(x=>x!==i):game.selected.push(i);return}if(e.target.id==="check-find"){const q=findQuestions[game.index],need=q.parts.map((p,i)=>p.type!=="normal"?i:-1).filter(i=>i>=0),ok=game.selected.length===need.length&&need.every(i=>game.selected.includes(i));game.locked=true;if(ok){q.parts.forEach((p,i)=>{const el=stage().querySelector(`[data-find="${i}"]`);if(p.type==="noon")el.classList.add("revealed-noon","is-correct");if(p.type==="rule-letter")el.classList.add("revealed-rule","is-correct")});game.score++;setAnswerLock(stage(),true);f.className="feedback good";f.innerHTML=celebrate(stage(),encourage(),"تم تحديد موضع النون أو التنوين والحرف المؤثر.");advance()}else{const selectedCards=[...stage().querySelectorAll(".find-part.selected")];selectedCards.forEach(card=>card.classList.add("is-wrong"));showWrong(null,stage(),f,"حدد الموضعين فقط: النون أو التنوين، والحرف الذي يليه.",()=>{selectedCards.forEach(card=>card.classList.remove("is-wrong"));game.locked=false})}return}
});

const theoryQuizBank=[
  ["كم عدد حروف الإظهار؟",["١","٤","٦","١٥"],"٦"],["ما حرف الإقلاب؟",["م","ب","ن","و"],"ب"],["أي كلمة تجمع حروف الإدغام؟",["ينمو","يرملون","قطب جد","أخي هاك"],"يرملون"],["ما حروف الإدغام بغير غنة؟",["ي، و","م، ن","ل، ر","ع، ح"],"ل، ر"],["كم عدد حروف الإخفاء؟",["٦","١٥","٤","١"],"١٥"],["أكمل كلمة حروف الإدغام: يرملـ…",["ون","ان","يم","بن"],"ون"],["غنة الإخفاء مقدارها…",["حركة","حركتان","أربع حركات","لا غنة"],"حركتان"],["أي حرف من حروف الإظهار؟",["ص","ب","خ","ت"],"خ"],["أي حرف من حروف الإخفاء؟",["ع","هـ","ق","ر"],"ق"]];
let quizBank=[];
let quiz=[],quizPos=0,quizScore=0,quizLocked=false;
function updateBest(){document.querySelector("#best-score").textContent=state.score?`أفضل نتيجة: ${toArabic(state.score)} / ١٠`:""}updateBest();
function buildQuizBank(activityKey){const exampleQuestions=balancedRuleExamples(6,activityKey).map(example=>["ما حكم المثال الآتي؟",["إظهار","إدغام بغنة","إدغام بغير غنة","إقلاب","إخفاء"],ruleDisplayName(example),example]);return [...fisherYates(theoryQuizBank).slice(0,4),...exampleQuestions]}
function startQuiz(){quizBank=buildQuizBank(exampleManager.nextActivityKey("quiz:final"));quiz=fisherYates(quizBank).slice(0,10);quizPos=0;quizScore=0;quizLocked=false;showQuiz()}
document.querySelector("#quiz-card").addEventListener("click",e=>{if(e.target.id==="start-quiz")return startQuiz();const option=e.target.closest("[data-quiz-answer]");if(!option||quizLocked)return;quizLocked=true;const card=document.querySelector("#quiz-card"),f=card.querySelector(".feedback"),ok=option.dataset.quizAnswer===quiz[quizPos][2];if(ok){quizScore++;showCorrect(option,card,f,encourage(),"إجابة صحيحة.")}else{option.classList.add("is-wrong");setAnswerLock(card,true);option.classList.remove("is-disabled");tone("wrong");f.className="feedback try";f.textContent=wrongText}setTimeout(()=>{quizPos++;quizLocked=false;quizPos<10?showQuiz():showResult()},2150)});
function showQuiz(){const q=quiz[quizPos];document.querySelector("#quiz-card").innerHTML=`<div class="quiz-question"><div class="quiz-meta"><b>السؤال ${toArabic(quizPos+1)} من ١٠</b><span>النتيجة في النهاية</span></div><div class="quiz-bar"><span style="width:${(quizPos+1)*10}%"></span></div><h3>${q[0]}</h3>${q[3]?`<div class="game-example">${renderParts(q[3].parts)}</div>`:""}<div class="quiz-options">${fisherYates(q[1]).map(o=>`<button class="quiz-option answer-card" data-quiz-answer="${o}">${o}</button>`).join("")}</div><div class="feedback"></div></div>`}
function showResult(){if(quizScore>state.score){state.score=quizScore;localStorage.setItem("tajweedScore",state.score)}updateBest();const msg=quizScore===10?"إتقان رائع!":quizScore>=8?"ممتاز جدًا!":quizScore>=6?"أداء جميل، بقي القليل!":"محاولة جميلة، لنكرر التحدي!";tone("level-complete");confetti();document.querySelector("#quiz-result-content").innerHTML=`<span class="logo-wrap"><img src="logo.jpeg" alt="شعار Milestone School"></span><strong>${toArabic(quizScore)} / ١٠</strong><h2>${msg}</h2><div class="result-actions"><button id="retry-quiz" class="primary-button">إعادة الاختبار</button><button class="soft-button" data-screen="games">الألعاب</button><button class="soft-button" data-screen="map">اختيار الأحكام</button></div>`;showScreen("quiz-result")}
document.querySelector("#quiz-result").addEventListener("click",e=>{if(e.target.id==="retry-quiz"){startQuiz();showScreen("quiz")}});

function updateSoundControl(){const button=document.querySelector("#sound-toggle");button.setAttribute("aria-pressed",state.sound);button.setAttribute("aria-label",state.sound?"كتم الصوت":"تشغيل الصوت");button.classList.toggle("muted",!state.sound)}
document.querySelector("#sound-toggle").addEventListener("click",()=>{state.sound=!state.sound;localStorage.setItem("tajweedSound",state.sound?"on":"off");if(!state.sound){sfxManager.stop();sfxManager.stopQuran()}updateSoundControl();if(state.sound)tone("click")});
updateSoundControl();
document.querySelector("#teacher-mode").addEventListener("click",e=>{const panel=document.querySelector("#teacher-panel"),opening=panel.hidden;state.teacher=opening;document.body.classList.toggle("teacher-on",state.teacher);e.currentTarget.classList.toggle("active",state.teacher);e.currentTarget.setAttribute("aria-expanded",opening);panel.hidden=!opening;toast(opening?"تم تشغيل إرشادات المعلّمة.":"تم إخفاء إرشادات المعلّمة.")});
document.querySelector("#reset-progress").addEventListener("click",()=>{if(confirm("هل تريد حذف التقدم ونتيجة الاختبار؟")){localStorage.removeItem("tajweedProgress");localStorage.removeItem("tajweedScore");location.reload()}});
